name:                haskell-parser
version:             0.1.0.0
github:              "daebr/haskell-parser"
license:             MIT
author:              "Ben Price"
maintainer:          ""
copyright:           "2020 Ben Price"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/daebr/haskell-parser#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - transformers
  - extra

tests:
  haskell-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-parser
    - regex-pcre
    - test-framework
    - test-framework-hunit
    - HUnit
